# Generated by Django 2.1.2 on 2019-12-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='image',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='user',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='user',
        ),
        migrations.AddField(
            model_name='emotion',
            name='comment',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emotion',
            name='image_url',
            field=models.URLField(default='aa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emotion',
            name='main_emotion',
            field=models.CharField(default='aaa', max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Archive',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
